### ISSUE TITLE
Unable to load alignment file

### ISSUE THREAD

**Issue by belafif2** [shenkers/CrossBrowse#4]
Hi @shenkers 

I am having trouble loading chain alignment files to CrossBrowse.
I am using the most recent release of CrossBrowse: `ComparativeBrowser-1.0-SNAPSHOT.jar`

The chain file was generated by converting a maf alignment file generated by LAST aligner into a chain alignment file. I am using the maf-convert script that is part of the LAST package.

I am attaching the log file when I tried to load my chain files here.

Thanks.
```
[JavaFX Application Thread] INFO org.mskcc.shenkers.controller.FXMLController - loading alignments
[JavaFX Application Thread] INFO org.mskcc.shenkers.controller.FXMLController - Selected alignment file: /Users/mbelaffif/Project/2017/miscanthus_JAZ_genes/results/last/msin-chr01-v-sbic.chain
[JavaFX Application Thread] INFO org.mskcc.shenkers.controller.FXMLController - Selected alignment file: /Users/mbelaffif/Project/2017/miscanthus_JAZ_genes/results/last/msin-chr02-v-sbic.chain
[JavaFX Application Thread] INFO org.mskcc.shenkers.controller.FXMLController - ButtonType [text=OK, buttonData=OK_DONE]
[JavaFX Application Thread] INFO org.mskcc.shenkers.controller.FXMLController - OK
[JavaFX Application Thread] INFO org.mskcc.shenkers.controller.FXMLController - preparing to load alignments
[JavaFX Application Thread] INFO org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1 - converting /Users/mbelaffif/Project/2017/miscanthus_JAZ_genes/results/last/msin-chr01-v-sbic.chain to /Users/mbelaffif/Project/2017/miscanthus_JAZ_genes/results/last/msin-chr01-v-sbic.chain.gff.bgz
[JavaFX Application Thread] INFO org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1 - /Users/mbelaffif/Project/2017/miscanthus_JAZ_genes/results/last/msin-chr01-v-sbic.chain.gff.bgz already exists? false
[JavaFX Application Thread] INFO org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1 - converting chain to gff
[JavaFX Application Thread] INFO htsjdk.samtools.liftover.ChainGFFConverter1 - scanning chain file
[JavaFX Application Thread] INFO htsjdk.samtools.liftover.ChainGFFConverter1 - 97863 chains counted
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$358(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	... 40 more
Caused by: java.lang.NumberFormatException: For input string: "chain"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at htsjdk.samtools.liftover.ChainGFFConverter1.convert(ChainGFFConverter1.java:142)
	at org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1.convertChainToGffBgz(ChainGFFAlignmentSource1.java:81)
	at org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1.<init>(ChainGFFAlignmentSource1.java:66)
	at org.mskcc.shenkers.control.alignment.io.AlignmentFileLoader.load(AlignmentFileLoader.java:26)
	at org.mskcc.shenkers.controller.FXMLController.lambda$null$20(FXMLController.java:922)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.mskcc.shenkers.controller.FXMLController.lambda$loadChainAlignment$22(FXMLController.java:922)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.mskcc.shenkers.controller.FXMLController.loadChainAlignment(FXMLController.java:917)
	... 50 more

```

**Comment by shenkers** [comment]
Hi @belafif2 , I have not used that program from the last package, but my guess is that it is something about the format of the chain file it does not like. I was loading chain files i downloaded from the UCSC genome browser, if you download a chain file from there, you could try and see if you can spot the difference in formatting between last and UCSC. My guess is it might be comment lines that LAST adds, but the parser does not know to ignore. If you can't figure it out, you can attach the chain file here and I can take a look.

**Comment by belafif2** [comment]
Based on you suggestion I compare the chain file generated by LAST and chain file from UCSC genome browser. Apparently the chain file generated by the script in the LAST pacakge did not have an empty line separating one chain entry from another chain entry. Modifying my chain file solved the problem

However I discovered a new problem. I can't seem to get CrossBrowse to display the synteny overlay. Inspection on the log file reported the following error when trying to display the regions inside the chain file. The specific regions are sorghum: Chr01:75412196-75436481 and miscanthus: Chr01:139721702-139789492

```
[Thread-9] INFO org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay - Adding alignments from msin-a (msin-a) to sorghum (sorghum)
[Thread-9] INFO org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay - querying from Chr01:139721702-139789492:+ to Chr01:75412196-75436481:+
[Thread-9] INFO org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1 - querying alignment file
[Thread-9] INFO org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1 - iterating alignments
[Thread-9] INFO org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay - 0 chains overlapping query region
[Thread-9] ERROR org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay - error constructing alignment from specified regions
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1447)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay.initializeWeaver(ChainAlignmentOverlay.java:98)
	at org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay.getAlignmentColumnsRelativeX(ChainAlignmentOverlay.java:170)
	at org.mskcc.shenkers.control.alignment.chain.ChainAlignmentOverlay.getOverlayPaths(ChainAlignmentOverlay.java:353)
	at org.mskcc.shenkers.control.alignment.AlignmentRenderer$2.call(AlignmentRenderer.java:143)
	at org.mskcc.shenkers.control.alignment.AlignmentRenderer$2.call(AlignmentRenderer.java:99)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$498(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$499(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Since this is a chromosome vs chromosome alignment, both the fasta and gtf files are huge. I upload the fasta of both species, their gtfs and the chain file in the following link for you to inspect:
[https://drive.google.com/file/d/1hVpXxmGgq-ysDRTk4LSSP1hwAgFpZjXu/view?usp=sharing](url)

**Comment by shenkers** [comment]
thanks @belafif2 , one problem down, at least.

It looks like the format of these files is fine, they are loaded correctly. I tried navigating to one of the regions for which a chain exists and it shows up fine:
![image](https://user-images.githubusercontent.com/2341961/54573539-16b63100-49c3-11e9-9de0-d180f46f4775.png)

Are you sure that the chain file contains an alignment between the two regions you are viewing? The error (NoSuchElementException) suggests that it was looking for an alignment, but was unable to find one. 

One thing to keep in mind is that the chain files have a polarity. The one you shared with me goes from Sbic -> Msin. The first time I loaded it, I loaded it the other way around, and when I used the liftover function it brought me to a region that was past the end of the contig in the fasta. Maybe you did the same thing?

When you load the alignment, you'll want to specify the polarity like this:
![image](https://user-images.githubusercontent.com/2341961/54573649-8cba9800-49c3-11e9-806b-1f2df30cb19f.png)

**Comment by shenkers** [comment]
Any luck with this @belafif2? Working on your end now? Find anything interesting?

**Comment by belafif2** [comment]
I think when I load my chain file, I put the polarity wrong. 

I was under the assumption that since the target in my chain file in Sbic and my query is Msin, the polarity should be Msin->Sbic. 
Clearly I misunderstood the polarity part. So after correcting for that I was able to load my alignment successfully. Here it is with the RNA-seq expression data loaded:

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/16949031/54781459-53b03c80-4bea-11e9-92e1-2ac57a93808b.png">

Thanks @shenkers

**Comment by shenkers** [comment]
nice! glad to hear it
