### ISSUE TITLE
First Load of alignment fails to generate .gff.bgz

### ISSUE THREAD

**Issue by qoldt** [shenkers/CrossBrowse#5]
Hi, 

Very cool package. I think it has a lot of potential.
I can load genomes and gtfs and bigwigs, but I'm having trouble loading the chain file (monDom5_to_mm10.chain, ~ 783 MB. downloaded from UCSC).  

The program tries to generate a .gff.bgz file, and java uses up to 2.2GB of RAM, but it looks like the process times out, and in the end the .gff.bgz file is zero kb.

Any idea how to fix this? I tried to find the indexing call to generate the .gff.bgz separately but I don't have much experience with java.

Andrew

**Comment by shenkers** [comment]
Hi Andrew, Are you starting crossbrowse from the command line? Are there any error messages that appear in the terminal? The first time the chain file is loaded it is converted to a tabix-indexed format that can be quickly queried later. If the file is empty, something it probably means there was some kind of error. If I had to guess, it might be something about the formatting of the chain file, which should show up as an error at the command line.

**Comment by qoldt** [comment]
Yes I couldn't even debug, as I cannot run from the command line, I get the same error as the others trying to run in linux: 
`Could not find or load main class org.mskcc.shenkers.controller.MainApp`

```
user@host:~$ jar tf ComparativeBrowser-1.0-SNAPSHOT.jar | grep MainApp
org/mskcc/shenkers/controller/MainApp.class
org/mskcc/shenkers/controller/MainApp$1.class
```

```
user@host:~$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-macosx) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-macosx) (build 25.121-b15, mixed mode)
```

**Comment by shenkers** [comment]
Ah, what platform are you using? There is a terminal you can use even if
you're on mac or windows.

The trouble with Linux is that the UI library I used is not distributed
with the default Java installation (openjdk). One solution is to install
the Oracle jdk, instead of using open jdk. I can look into how to get it
running with openjdk, but will also likely require installation of an extra
package or two.

**Comment by qoldt** [comment]
mac OSX 10.13.6
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-macosx) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-macosx) (build 25.121-b15, mixed mode)

I'll give it a shot with oracle jdk

**Comment by shenkers** [comment]
And how are you starting it to load the genome, bigWig, and gtf? double clicking? To see the command-line output on a mac you'll need to go into applications -> utilities -> terminal

at the command line, to start crossbrowse you would type

java -jar [path to crossbrowse jar]

if you have multiple versions of java installed on your system, you might need to tell it explicitly to use the oracle version of java, e.g.:

[path to oracle java] -jar [path to crossbrowse jar]

**Comment by qoldt** [comment]
using oracle-jdk 1.8.0_261

```
[JavaFX Application Thread] INFO org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1 - converting chain to gff
[JavaFX Application Thread] INFO htsjdk.samtools.liftover.ChainGFFConverter1 - scanning chain file
[JavaFX Application Thread] INFO htsjdk.samtools.liftover.ChainGFFConverter1 - 8953638 chains counted
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$6(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	... 40 more
Caused by: java.lang.NumberFormatException: For input string: "CGV"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at htsjdk.samtools.liftover.ChainMergeSort.loadChain(ChainMergeSort.java:126)
	at htsjdk.samtools.liftover.ChainMergeSort$1ChainKeyFunction.extractKey(ChainMergeSort.java:95)
	at htsjdk.samtools.liftover.ChainMergeSort$1ChainKeyFunction.extractKey(ChainMergeSort.java:78)
	at htsjdk.samtools.liftover.MergeSort$SortedFile.poll(MergeSort.java:228)
	at htsjdk.samtools.liftover.MergeSort$SortedFile.<init>(MergeSort.java:213)
	at htsjdk.samtools.liftover.MergeSort.merge(MergeSort.java:185)
	at htsjdk.samtools.liftover.MergeSort.close(MergeSort.java:162)
	at htsjdk.samtools.liftover.ChainGFFConverter1.convert(ChainGFFConverter1.java:163)
	at org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1.convertChainToGffBgz(ChainGFFAlignmentSource1.java:81)
	at org.mskcc.shenkers.control.alignment.chain.ChainGFFAlignmentSource1.<init>(ChainGFFAlignmentSource1.java:66)
	at org.mskcc.shenkers.control.alignment.io.AlignmentFileLoader.load(AlignmentFileLoader.java:26)
	at org.mskcc.shenkers.controller.FXMLController.lambda$null$20(FXMLController.java:922)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.mskcc.shenkers.controller.FXMLController.lambda$loadChainAlignment$22(FXMLController.java:922)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.mskcc.shenkers.controller.FXMLController.loadChainAlignment(FXMLController.java:917)
	... 50 more
```

This is the head of my chain file (monDom5 to mm10), the format appears correct:

```
chain 130810000 chr4 435153693 + 137689323 203593546 chr2 182113224 + 39592253 84454496 1
54	0	3
33	2	0
12	3	0
14	0	2
46	1	0
24	1	0
54	464	882
9	0	7
44	0	12
```

I also tried starting the .jar with a large amount of RAM and I get the same result.

**Comment by shenkers** [comment]
Thank you! It looks like it's trying to parse a field somewhere that has the text "CGV" as a decimal number. If you search through your chain file, do you see any lines that have CGV?

if you're using the command line, you could use `grep -C 10 CGV [path to chain file]`

this is the part of the error message that makes me think it's a parsing problem:
```
Caused by: java.lang.NumberFormatException: For input string: "CGV"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
```
